version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd # 设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /tmp/mydata/mysql/data/db:/var/lib/mysql # 数据文件挂载
      - /tmp/mydata/mysql/data/conf:/etc/mysql/conf.d # 配置文件挂载
      - /tmp/mydata/mysql/log:/var/log/mysql # 日志文件挂载
  nginx:
    image: nginx:1.10
    container_name: nginx
    volumes:
      # - /tmp/mydata/nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - /tmp/mydata/nginx/conf:/etc/nginx # 配置文件挂载
      - /tmp/mydata/nginx/html:/usr/share/nginx/html # 静态资源根目录挂载
      - /tmp/mydata/nginx/log:/var/log/nginx # 日志文件挂载
    ports:
      - 80:80
  redis:
    image: redis:3.2
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /tmp/mydata/redis/data:/data # 数据文件挂载
    ports:
      - 6379:6379
  elasticsearch:
    image: elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" # 设置集群名称为elasticsearch
      - "discovery.type=single-node" # 以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 设置使用jvm内存大小
    volumes:
      - /tmp/mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins # 插件文件挂载
      - /tmp/mydata/elasticsearch/data:/usr/share/elasticsearch/data # 数据文件挂载
    ports:
      - 9200:9200
#      - 9300:9300 # cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
  kibana:
    image: kibana:6.4.0
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  mongo:
    image: mongo:3.2
    container_name: mongo
    volumes:
      - /tmp/mydata/mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    volumes:
      - /tmp/mydata/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - /tmp/mydata/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
